### ISSUE TITLE
Window scales too small

### ISSUE THREAD

**Issue by bcm314** [Bubu/android-dice-game#2]
The window scales too small, as also others telling here:
http://web.archive.org/web/20140110202858/https://play.google.com/store/apps/details?id=com.ridgelineapps.resdicegame

So I suggest to remove the limitation of upscaling.

Doing in this way:
in file GameView.java search for

	if(xScale > 1 && yScale > 1 && screenInches >= 6) {

Replace it with

	if(false) {

would do the job in simplest way.
(Alternatively you should add an option in the app-settings to enabled/dissable this feature.)

**Comment by Bubu** [comment]
Thanks for the report. I\m trying to understand how the scaling works right now. Or rather how it's constrained. 
Always upscaling might look bad on really high resolutions though?

I thinkt the best option is to redo the assets in higher resolution (and not use the catan ones at that...).
In the mean time I'll look into making this an option/button.

**Comment by bcm314** [comment]
I know, making it looking well on all devices (especially one you don't own) is a very hard thing.
So I was looking at the original code again and also made tests on all my devices.
On my new (5 inch) and old (4 inch) smartphone it will displayed fullscreen.
On both tablets (10 inch) it's scaled down - too small.
Understanding the code, that only on devices "screenInches >= 6" (screen size, not resolution) it will be shown too small.

Always scaling is depending on usage:
if one has a 50 inch TV and is sitting directly in front of it, it should be scaled down.
Sitting on a sofa a few meters away, better upscale it.

Of course the best option is always to have high resolution images (but need an artist).
Removing catan images would also be a good thing, because there must be problems with copyright (and I strongly guess, this was the reason the app was removed from google play store).
Furthermore also changing the rules a little bit could help being on save side. Also could make the game more interesting and thrilling.
