### ISSUE TITLE
City building rules

### ISSUE THREAD

**Issue by ypnos** [Bubu/android-dice-game#6]
I never managed to build a city in this game.  For example please have a look at this this situation:

![screenshot_20170725-183011](https://user-images.githubusercontent.com/8481470/28583151-6df05070-7168-11e7-9449-964857e07f10.png)

I would expect to be able to build the 12pt city in the top left.

**Comment by Bubu** [comment]
You need to build the cities in order, so the 7 pt city before the 12 pt one. And you can't build the 7 pt. city because there is no road up to it.

I'll see if it's made clear in the rules text.

**Comment by Bubu** [comment]
Yep, it's in the rules. Do you have any suggestions how to make the behaviour more intuitive?

**Comment by ypnos** [comment]
First of all I am stupid, I didn't realize there is more rules text after the image. I read the manual of the original game to figure it out instead. Second, I must have missed that detail from the rules. Thank you for the clarification.

What I do suggest however is to not only indicate visually which entities could be built with the current roll, but also which entities could be theoretically built at this point of the game (reachable targets if you get a lucky roll). For me it took a while to realize what the green stuff means in the first place. Reachable targets could have the number text in a fat font, or different color. Although it is implicitely given, also the available knight guarded resources could be visually distinguished. Finally, the rules explanation could have a legend of the different color codes (already built, reachable, clickable, …)
